# Generated by Django 4.2.4 on 2024-01-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bannerapp', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
